version: "3.8"

services:
  orm:
    build:
      context: .  # Ruta al directorio que contiene tu Dockerfile
      dockerfile: Dockerfile  # Opcional si el nombre es distinto
    container_name: orm_app
    volumes:
      - ./factiva_data/pre:/app/sql  # Monta los scripts SQL en /app/sql dentro del contenedor
    env_file:
      - .env  # Carga variables de entorno desde .env
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy  # Espera a que MySQL esté listo antes de iniciar
    networks:
      - app_net

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: TEST
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: DBTEST
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  mysql_data:
