
DROP TABLE IF EXISTS DESCRIPTION1_LIST_DATA;
CREATE TABLE DESCRIPTION1_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  Description1Id VARCHAR(10),
  RecordType VARCHAR(255),
  value VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS DESCRIPTION2_LIST_DATA;
CREATE TABLE DESCRIPTION2_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  Description1Id VARCHAR(10),
  Description2Id VARCHAR(10),
  value VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS DESCRIPTION3_LIST_DATA;
CREATE TABLE DESCRIPTION3_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  Description2Id VARCHAR(10),
  Description3Id VARCHAR(10),
  value VARCHAR(255),
  date DATE
);


DROP TABLE IF EXISTS COUNTRY_LIST_DATA;
CREATE TABLE COUNTRY_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  code VARCHAR(255),
  name VARCHAR(255),
  IsTerritory VARCHAR(5),
  ProfileURL VARCHAR(255),
  date DATE
);


DROP TABLE IF EXISTS OCCUPATION_LIST_DATA;
CREATE TABLE OCCUPATION_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  code VARCHAR(255),
  name VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS RELATIONSHIP_LIST_DATA;
CREATE TABLE RELATIONSHIP_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  code VARCHAR(255),
  name VARCHAR(255),
  date DATE
);


DROP TABLE IF EXISTS SANCTION_REFERENCE_LIST_DATA;
CREATE TABLE SANCTION_REFERENCE_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  code VARCHAR(255),
  name VARCHAR(255),
  status VARCHAR(255),
  Description2Id VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS DATE_TYPE_LIST_DATA;
CREATE TABLE DATE_TYPE_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  DateTypeID VARCHAR(10),
  name VARCHAR(255),
  RecordType VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS NAME_TYPE_LIST_DATA;
CREATE TABLE NAME_TYPE_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  NameTypeID VARCHAR(10),
  RecordType VARCHAR(255),
  value VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS ROLE_TYPE_LIST_DATA;
CREATE TABLE ROLE_TYPE_LIST_DATA (
  id VARCHAR(10) NOT NULL,
  list_tag VARCHAR(255),
  tag VARCHAR(255),
  RoleTypeID VARCHAR(10),
  name VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS COUNTRY_DETAILS_DATA;
CREATE TABLE COUNTRY_DETAILS_DATA (
  data_id VARCHAR(10),
  type VARCHAR(255),
  country_type VARCHAR(255),
  code VARCHAR(10),
  date DATE
);

DROP TABLE IF EXISTS NAME_DETAILS_DATA;
CREATE TABLE NAME_DETAILS_DATA (
  data_id VARCHAR(10),
  type VARCHAR(255),
  name_type VARCHAR(255),
  first_name VARCHAR(255),
  middle_name VARCHAR(255),
  surname VARCHAR(255),
  entity_name VARCHAR(255),
  suffix VARCHAR(255),
  org_script_name VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS DESCRIPTION_DETAILS_DATA;
CREATE TABLE DESCRIPTION_DETAILS_DATA (
  data_id VARCHAR(10),
  type VARCHAR(255),
  description1 VARCHAR(255),
  description2 VARCHAR(255),
  description3 VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS ROLE_DETAILS_DATA;
CREATE TABLE ROLE_DETAILS_DATA (
  data_id VARCHAR(10),
  type VARCHAR(255),
  role_type VARCHAR(255),
  since_day VARCHAR(255),
  since_month VARCHAR(255),
  since_year VARCHAR(255),
  to_day VARCHAR(255),
  to_month VARCHAR(255),
  to_year VARCHAR(255),
  occ_tittle_category VARCHAR(255),
  occ_tittle_desc VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS DATE_DETAILS_DATA;
CREATE TABLE DATE_DETAILS_DATA (
  data_id VARCHAR(10),
  type VARCHAR(255),
  date_type VARCHAR(255),
  year VARCHAR(255),
  month VARCHAR(255),
  day VARCHAR(255)
);

DROP TABLE IF EXISTS IMAGE_DETAILS_DATA;
CREATE TABLE IMAGE_DETAILS_DATA (
  data_id VARCHAR(10),
  type VARCHAR(255),
  image_type VARCHAR(255),
  url VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS SANCTION_REFERENCE_DETAILS_DATA;
CREATE TABLE SANCTION_REFERENCE_DETAILS_DATA (
  data_id VARCHAR(10),
  type VARCHAR(255),
  sanction_reference_type VARCHAR(255),
  since_day VARCHAR(255),
  since_month VARCHAR(255),
  since_year VARCHAR(255),
  to_day VARCHAR(255),
  to_month VARCHAR(255),
  to_year VARCHAR(255),
  reference_code VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS COMPANY_DETAILS_DATA;
CREATE TABLE COMPANY_DETAILS_DATA (
  data_id VARCHAR(10) NOT NULL,
  type VARCHAR(255),
  address_type VARCHAR(255),
  address_line VARCHAR(255),
  address_city VARCHAR(255),
  address_country VARCHAR(255),
  address_url VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS ID_DETAILS_DATA;
CREATE TABLE ID_DETAILS_DATA (
  data_id VARCHAR(10) NOT NULL,
  type VARCHAR(255),
  id_type VARCHAR(255),
  value VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS SOURCE_DETAILS_DATA;
CREATE TABLE SOURCE_DETAILS_DATA (
  data_id VARCHAR(10) NOT NULL,
  type VARCHAR(255),
  source_type VARCHAR(255),
  name VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS DATA;
CREATE TABLE DATA (
  data_id VARCHAR(10) NOT NULL,
  type VARCHAR(255),
  action VARCHAR(255),
  action_date VARCHAR(255),
  gender VARCHAR(255),
  active_status VARCHAR(255),
  deceased VARCHAR(255),
  profile_notes VARCHAR(255),
  date DATE
);

DROP TABLE IF EXISTS ASSOCIATIONS_DATA;
CREATE TABLE ASSOCIATIONS_DATA (
  data_id VARCHAR(10),
  record_type VARCHAR(255),
  associated_record_id VARCHAR(10),
  code VARCHAR(10),
  ex_status VARCHAR(10),
  date DATE
);
